manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: temper
      url: https://github.com/raeedcho/temper-zmk-config
      revision: 2196e7a30f8b4851d964894c897f8625d8f15cc1
  self:
    path: config
